micronaut:
  application:
    name: mn
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      event-loop-group: other

netty:
  default:
    allocator:
      max-order: 3

bookUrl: "https://raw.githubusercontent.com/kevind-wgu/mn-client-test/main/books/book2.json"